# Generated by Django 5.0 on 2024-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.TextField(blank=True, choices=[('0', 'default'), ('1', 'low'), ('2', 'medium'), ('3', 'high')], default='0', max_length=1),
        ),
    ]
